name: daily_update

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 8 * * *
  release:
    types: [published]

jobs:
  merge_upstream:
    name: 更新CF数据
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
          lfs: true

      - name: Set git config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global pull.rebase false
          git config --global --list

      - name: pip install
        run: |
          pip install httpx pandas openpyxl

      - name: update codeforces data
        run: python3 main.py

      - name: Push Commits
        env:
          DOWNSTREAM_BRANCH: master
        run: |
          git add --all
          git commit -m "Daily Auto Update"
          git push origin $DOWNSTREAM_BRANCH